#!/bin/sh
[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    # Fall back to using the very slow lsb_release utility
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

DOMAIN="$(hostname | cut -d '.' -f 2-)"

printf "%s" "$(figlet $(hostname | cut -d '.' -f 1))" | sed -e 's/[[:space:]]*$//' | sed '${s/$/.'"${DOMAIN}"'/}' | lolcat -f
printf "\n"

printf "Welcome to %s (%s).\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
printf "\n"
