#!/bin/sh

[ -r /etc/hostname ] && HOSTNAME=$(cat /etc/hostname) || HOSTNAME=$(hostname)
HOST_PFX="${HOSTNAME%%.*}"
HOST_DOMAIN="${HOSTNAME#*.}"

[ -r /usr/lib/os-release ] && . /usr/lib/os-release || . /etc/os-release

if [ -n "$PRETTY_NAME" ]; then
    OS_NAME="$PRETTY_NAME"
elif [ -n "$NAME" ]; then
    OS_NAME="$NAME"
else
    [ -r /etc/lsb-release ] && . /etc/lsb-release

    if [ -n "$DISTRIB_DESCRIPTION" ]; then
        OS_NAME="$DISTRIB_DESCRIPTION"
    elif command -v lsb_release >/dev/null; then
        OS_NAME=$(lsb_release -s -d)
    else
        OS_NAME="Unknown System"
    fi
fi

[ -n "$ANSI_COLOR" ] && OS_NAME="\033[${ANSI_COLOR}m${OS_NAME}\033[m"

figlet "$HOST_PFX" | sed -e 's/[[:space:]]*$//;${s/$/.'"${HOST_DOMAIN}"'/}' | lolcat -f
env echo -e "\nWelcome to ${OS_NAME} $(uname -r)\n"